### ISSUE TITLE
Document all 4 fonts in the README

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/mplhep_data#23]
Indeed there are 4 available (https://github.com/scikit-hep/mplhep_data/tree/master/src/mplhep_data/fonts) but only 3 documented in the README so far. WDYT?

**Comment by andrzejnovak** [comment]
Imo not high prio since this is not user-facing and the license is included correctly, but PR welcome.

**Comment by eduardo-rodrigues** [comment]
I would have done it immediately had I known the link myself ;-). I have not been playing with the fonts, and will have to check ... Of course this is no priority but a nice thing to have. It may take you 3 minutes.
